package vn.edu.clevai.bplog.payload.request;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Builder
public class WUTRequest {
	private String ulcUlccode;
	private String ulcMycap;
	private String ulcLcpcode;
	private String ulcMylct;
	private String ulcMyjointudl;
	private String ulcPublished;
	private String gcAcyear;
	private String gcTerm;
	private String gcPt;
	private String gcGg;
	private String gcWkno;
	private String gcDyno;
	private String gcCrpp;
	private String gcCrps;
	private String gcCuwk;
	private String gcCudy;
	private String gcCush;
	private String gcDfdl;
	private String gcLct;
	private String gcSsno;
	private String gcDfge;
	private String gcScno;
	private String gcCuss;
	private String gcCusc;
	private String gcSsl;
	private String gcBl3qg;
	private String gcBl5qp1;
	private String gcBl5qp2;
	private String gcBl5qp3;
	private String clagClagcode;
	private String clagMypt;
	private String clagMygg;
	private String clagMywso;
	private String clagMydfdl;
	private String clagMydfge;
	private String clagMyclagUlc;
	private String sussCass;
	private String sussLcp;
	private String sussClaglist;
	private String sussTe;
	private String sussEm1;
	private String sussEm2;
	private String sussEm3;
	private String sussCti;
	private String cuiCuicode;
	private String cuiUlccode;
	private String cuiMylcp;
	private String cuiUsicode;
	private String cuiUst;
	private String cuiMycti;
	private String cuiPodpcode;
	private String cuiMypodpparent;
	private String cuiMypod;
	private String cuiPublished;
	private String cuieCuiecode;
	private String cuieMylcet;
	private String cuiePlantime;
	private String cuieActualtime;
	private String cuieCuicode;
	private String cuieMyusi;
	private String cuieMycti;
	private String cuieMylcp;
	private String cuieMylct;
	private String cuiePublished;
	private String stStcode;
	private String stMygg;
	private String podPodcode;
	private String podMyst;
	private String podMypt;
	private String podMygg;
	private String podMywso;
	private String podMydfdl;
	private String podMyclagperm;
	private String podMyclagdyn;
	private String podMydfge;
	private String podMycombood;
	private String chptChptcode;
	private String chptMylct;
	private String chptMylcet;
	private String chptMyusttrigger;
	private String chptMyustsup;
	private String chptMychpttype;
	private String chstChstcode;
	private String chstMychpt;
	private String chstMychlt;
	private String chstMychrt;
	private String chstChstCti;
	private String chpiChpi;
	private String chpiChsi;
	private String chpiChli;
	private String chpiChri;
	private String chpiCti;
	private String chsiCti;
}
