package vn.edu.clevai.bplog.common.enumtype;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BpeEventTypeEnum {

	CREATE_CUIE_JOIN_REQUEST_PLAINTIME_OF_TE("102322C Create CUIEvent.JoinRequest Plantime of TE"),
	CREATE_CUIE_JOIN_REQUEST_PLAINTIME_OF_TO("102332C Create CUIEvent.JoinRequest Plantime of TO"),
	CREATE_CUIE_JOIN_REQUEST_PLAINTIME_OF_CO("102342C Create CUIEvent.JoinRequest Plantime of CO"),
	CREATE_CUIE_JOIN_REQUEST_PLAINTIME_OF_SO("102352C Create CUIEvent.JoinRequest Plantime of SO"),
	CREATE_CUIE_PLAINTIME_OF_ST("102365C Create CUIEvent Plantime of ST"),
	UNPUBLISH_CUIEVENT_TE("5275-UnPublish-CuiEvent-JoinRequest-TE-ActualTime"),
	PUBLISH_CUIEVENT_TE("5279-Publish-CuiEvent-JoinRequest-TE-ActualTime"),
	WRITE_CUIEVENT_JOIN_REQUEST_GE_DLG("5114-Write-CUIEvent-JoinRequest-ActualTime"),
	WRITE_CUIEVENT_JOIN_REQUEST_GE_GES("5214-Write-CUIEvent-JoinRequest-ActualTime"),
	CREATE_CUIEVENT_JOIN_REQUEST_GE_TE("5256-Create CuiEvent-JoinRequest-TE-ActualTime"),
	CREATE_CUIEVENT_CHANGE_CLAG("5269-Create-CuiEvent-JoinRequest-TE-ActualTime"),
	SET_PUBLISH_CUI_EVENTS("1175setPublishedCUIEvents"),
	SUBMIT_REPORT2("46122-Create-CuiEvent-SubmitReport2"),
	RECEIVE_SPEAKOUT_ST("46131-Create-CUIEvent-ReceiveSpeakOut-ST"),
	SUBMIT_REPORT1("454Find-CUIEvent-SubmitReport1-TE"),
	CREATE_CUIEVENT_JOIN_SUCCESSFUL_ST("4551-Create-CUIEvent-Join-Successful-ST"),
	CREATE_CUIEVENT_JOINREQUEST_ST("4715-Create-CUIEvent-JoinRequest-ST"),
	FIND_CUIEVENT_SUBMITREPORT3_TE("4714-Find-CUIEvent-SubmitReport3-TE"),
	WRITE_CUIEVENT_TIMEUP_TE_ACTUAL_TIME("623-Write-CUIEvent-Timeup-TE-Actual-Time"),
	FINDCUI_MAIN_CUIEVENT_ASSIGNVIDEO("83112-FindCUI-Main-CUiEvent-AssignVideo"),
	WRITE_CUIEVENT_AUDITVIDEO_TO_ACTUAL_TIME("83115-Write-CUIEvent-AuditVideo-TO-Actual-Time"),
	WRITE_CUI_EVENT_JOIN_REQUEST("4831Write CuiEvent-Join.Request - ActualTime"),
	CREATE_CUIEVENT_JOIN_SUCCESSFUL("53522-Create CuiEvent-JoinSuccessful-TE-ActualTime"),
	CREATE_CUI_BPPODCLAG_WITH_UST_EQUAL_DTE("Create cui(ust=dte)"),
	CREATE_CUI_BPPODCLAG_WITH_UST_EQUAL_CTE("Create cui(ust=cte, ulc = udct)"),
	CREATE_CUI_BPPODCLAG_WITH_UST_EQUAL_UGE("Create cui(ust=gte)"),
	CREATE_CUI_BPPODCLAG_WITH_UST_EQUAL_LTE("Create cui(ust=lte)"),
	CREATE_CUI_BPPODCLAG_BACKUP("Create cui"),

	CREATE_CUIE_BPPODCLAG_WITH_UST_EQUAL_DTE("161124createCuiE(UDL, POD);"),
	CREATE_CUIE_BPPODCLAG_WITH_UST_EQUAL_CTE("161330createCuiE(POD, UCO);"),
	CREATE_CUIE_BPPODCLAG_WITH_UST_EQUAL_UGE("161224createCuiE(UGE, POD);"),
	CREATE_CUIE_BPPODCLAG_WITH_UST_EQUAL_LTE("161424createCuiE(ULI, POD);"),
	CREATE_CUIE_BPPODCLAG_BACKUP("162134createCuiE(POD, UBW);"),
	BPEScheduleCAWK1("8976-BPEScheduleCAWK1"),

	ASSIGN_EM_CREATE_CUIE_UDL_POD("171123createCuiE(UDL, POD);"),
	ASSIGN_EM_CREATE_CUIE_UGE_POD("172000Assign-EM(TO,SO)-UGE"),
	ASSIGN_EM_CREATE_CUIE_UCO_POD("173000Assign-EM(TO,SO)-UCO"),
	ASSIGN_EM_CREATE_CUIE_ULI_POD("174000Assign-EM(TO,SO)-ULI"),
	CREATE_CUIE_FOR_MAIN_ACG_CAMN("87201-createCuieForMain(ULC, CTI)"),
	CREATE_CUIE_FOR_ST_ACG_CAMN("87221-createCuieForSt(ULC, POD)"),
	CREATE_CUIE_FOR_MAIN_ECG_CAMN("8738-createCuiForMain(ULC, CTI)"),
	CREATE_CUIE_FOR_ST_ECG_CAMN("8740-createCuiForSt(ULC, POD)"),
	CREATE_CUIE_FOR_MAIN_EPOD_NO_NOLCP_CAMN("8756-createCuiForMain(ULC, CTI)"),
	CREATE_CUIE_FOR_ST_EPOD_NO_NOLCP_CAMN("8757-createCuiForSt(ULC, POD)"),
	CREATE_CUIE_FOR_MAIN_EPOD_CAMN("8771-createCuiForMain(ULC, CTI)"),
	CREATE_CUIE_FOR_ST_EPOD_CAMN("8772-createCuiForST(ULC, POD)")
	;

	private final String code;

}
