package vn.edu.clevai.bplog.common.enumtype;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BppProcessTypeEnum {

	BPPSCHEDULE_UDLC("100#BPPSchedule-UDLC"),
	BPPSCHEDULE_UDLC01("102##BPPSchedule-UDLC01"),
	BPPSCHEDULE_UDLC02("101##BPPSchedule-UDLC02"),
	BPPSCHEDULE_UDLC03("103##BPPSchedule-UDLC03"),
	BPPSCHEDULE_UDLG("110#BPPSchedule-UDLG"),
	BPPSCHEDULE_UGES("120#BPPSchedule-UGES"),
	BPPSCHEDULE_USS("102#BPPSchedule-USS"),
	BPP_JOIN_REQUEST_GE_DLG("510#BPPJoinRequest-GE-DLG-ST"),
	BPP_JOIN_REQUEST_GE_GES("520#BPPJoinRequest-GE-GES-ST"),
	BPP_JOIN_REQUEST_GE_TE("525#BPPJoinRequest-GE-TE"),
	BPP_CHANGE_CLAG("526#BPPChangeCLAG-GE-GES-TE"),
	BPP_CHANGE_TE("527#BPPChangeTE"),
	BPP_TOGGLE_PUBLISHED_USH("11602#BPPTogglePublishedUSH"),
	SET_PUBLISHED_USS_117("117#setPublishedUSS"),
	BPPSUBMITREPORT2_TE_GE("460#BPPSubmitReport2-TE-GE[DLG/GES]"),
	BPPSUBMITREPORT1_TO("530#BPPSubmitReport1-TO"),
	BPPSUBMITREPORT1_TE_GE("450#BPPSubmitReport1-TE-GE[DLG/GES]"),
	BPPSUBMITREPORT3_TE_GE("470#BPPSubmitReport3-TE-GE[DLG/GES]"),
	BPPFINISH_GE("600#BPPFinish-GE[DLG,GES]"),
	BPPASSIGNVIDEO_GE("830#BPPAssignVideo-GE[DLG,GES]"),
	BPP_JOIN_REQUEST_DL("480#BPPJoinRequest-DL"),
    BPPASSIGN_TEMAIN("161000BPPAssign-TEMain()"),
    BPP_ASSIGN_TE_BACKUP("162000BPPAssign-TEBackup()"),
	BPP_SCHEDULE_CAWK("8800#BPPScheduleCAWK"),
	BPPASSIGN_EM("170000BPPAssign-EM"),
	BPPSCHEDULE_CAMN("8200#BPPScheduleCAMN(inputDate)"),
	BPPSCHEDULEMC_CAMN("8210#BPPScheduleMC(CAMN)")
	;
	private final String code;

}
