package vn.edu.clevai.bplog.common.enumtype;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BpsStepTypeEnum {

	A_CREATE_UDLC("1011A Create UDLC"),
	A_CREATE_UDLG("1111A Create UDLG"),
	SUGGEST_CLAG_UGE("1032Suggest CLAG-UGE"),
	A_CREATE_UGES("1211A Create UGES"),
	A_CREATE_USS("1021A Create USS"),
	SET_CLAG_ULC("1022Set CLAG-ULC"),
	CREATE_CUI_USS_OF_TE("102321B Create CUI USS Of TE"),
	CREATE_CUI_USS_OF_TO("102331B Create CUI  USS Of TO"),
	CREATE_CUI_USS_OF_CO("102341B Create CUI  USS Of CO"),
	CREATE_CUI_USS_OF_SO("102351B Create CUI  USS Of SO"),
	CREATE_CUI_USS_OF_ST("102364B Create CUI  USS Of ST"),
	UNPUBLISH_CUIEVENT_TE("5275-UnPublish-CuiEvent-JoinRequest-TE-ActualTime"),
	PUBLISH_CUIEVENT_TE("5279-Publish-CuiEvent-JoinRequest-TE-ActualTime"),
	CREATE_CUI_GE_DLC("5112-Create-CUI"),
	CREATE_CUI_GE_GES("5212-Create-CUI"),
	CREATE_CUI_GE_TE("5255-Create-CUI"),
	CREATE_CUI_CHANGE_CLAG("5267Create CUI"),
	CALL_SET_CLAGDYN_UGE_GE_DLG("5105-Call-setCLAGDYN-UGE-(CLAGDYN,UGE)"),
	CALL_SET_CLAGDYN_UGE_GE_GES("5205-Call-setCLAGDYN-UGE-(CLAGDYN,UGE)"),
	SET_PUBLISHED_USS_1171("1171setPublishedUSS"),
	SET_PUBLISH_CUIS("1173setPublishedCUIs"),
	FIND_CUI("4612-Find-CUIEvent-SubmitReport2-TE"),
	FOR_EACH_USI("4613-FOR-EACH-USI-STx12"),
	FIND_CUIEVENT_SUBMITREPORT1_TE("454-Find-CUIEvent(SubmitReport1)-TE"),
	CREATE_CUIEVENT_JOIN_SUCCESSFUL_ST("4551-Create-CUIEvent-Join-Successful-ST"),
	FIND_CUIEVENT_SUBMITREPORT3_TE("4714-Find-CUIEvent-(SubmitReport3)-TE"),
	CREATE_CUIEVENT_JOINREQUEST_ST("4715-Create-CUIEvent-JoinRequest-ST"),
	CUI_OF_TE_FINISH_CLICK("620-CUI-of-TE-Finish-Click-"),
	GETUSI("8311-GetUSI"),
	GET_USI("481GetUSI (ST)"),
	FIND_CUI_TO_SO("53531-FindCui-SO"),
	FIND_CUI_TO_TE("53521.FindCui-TE"),
    ASSIGN_TEMAIN_UDL_CADY("161100Assign-TEMain-UDL(CADY)"),
    ASSIGN_TEMAIN_UGE_CADY("161200Assign-TEMain-UGE(CADY)"),
    ASSIGN_TEMAIN_UCO_CADY("161300Assign-TEMain-UCO(CADY)"),
    ASSIGN_TEMAIN_ULI_CADY("161400Assign-TEMain-ULI(CADY)"),
    ASSIGN_TEBACKUP_USI_CADY("162100Assign-TEBackup-USI()"),
	BPSScheduleCAWK1("8861-BPSScheduleCAWK1"),
	BPSScheduleCAWK2("8864-BPSScheduleCAWK2"),
	BPSScheduleCAWK3("8944-BPSScheduleCAWK3"),
	BPSScheduleCAWK4("8976-BPSScheduleCAWK4"),
	ASSIGN_EM_TO_SO_QO_UDL("171000Assign-EM(TO,SO,QO)-UDL"),
	ASSIGN_EM_TO_SO_UGE("172000Assign-EM(TO,SO)-UGE"),
	ASSIGN_EM_TO_SO_UCO("173000Assign-EM(TO,SO)-UCO"),
	ASSIGN_EM_TO_SO_ULI("174000Assign-EM(TO,SO)-ULI"),
	SET_ULC_ACG_CAMN("8716-ULC = setULC( parentUlc, code = ULC_CODE,...)"),
	SET_ULC_ECG_CAMN("8735-ULC = setULC( parentUlc, code = ULC_CODE,...)"),
	SET_ULC_EPOD_NO_NOLCP_CAMN("8755-ULC = setULC( parentUlc, code = ULC_CODE,...)"),
	SET_ULC_EPOD_CAMN("8769-ULC = setULC( parentUlc, code = ULC_CODE,...)")
;
	private final String code;

}
